services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Country/City
      - REDIS_HOST=/var/run/redis/redis.sock
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=yourpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - /opt/nextcloud/config:/config
      - /opt/nextcloud/data:/data
      - ./redis:/var/run/redis
    ports:
      - 8080:80
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=yourpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=yourpass
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    command: redis-server --unixsocket /var/run/redis/redis.sock --unixsocketperm 770
    volumes:
      - ./redis:/var/run/redis
    restart: unless-stopped

  imaginar:
    image: h2non/imaginary
    container_name: imaginary
    command: -enable-url-source -mount /mnt/data
    volumes:
      - /opt/nextcloud/data:/mnt/data
    ports:
      - 9000:9000
    restart: unless-stopped

