services:
  db:
    image: mysql:8
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_PASSWORD: example_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    networks:
      - nextcloud-net

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    volumes:
      - redis_socket:/var/run/redis
    command: redis-server --unixsocket /var/run/redis/redis.sock --unixsocketperm 770
    networks:
      - nextcloud-net

  imaginary:
    image: h2non/imaginary
    container_name: nextcloud-imaginary
    restart: always
    ports:
      - "9000:9000"
    command: -enable-url-source -mount /data
    networks:
      - nextcloud-net

  app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_PASSWORD: example_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: /var/run/redis/redis.sock
      REDIS_HOST_TYPE: unix
      IMAGINARY_URL: http://imaginary:9000
    depends_on:
      - db
      - redis
      - imaginary
    networks:
      - nextcloud-net

volumes:
  db_data:
  nextcloud_data:
  redis_socket:

networks:
  nextcloud-net:
    driver: bridge

