services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /opt/nextcloud/config:/config
      - /opt/nextcloud/data:/data
    ports:
      - 8081:80
    depends_on:
      - db
      - redis
      - imaginary
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: nextcloud-db

    environment:
      - MYSQL_ROOT_PASSWORD=your_pass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_pass
      - MYSQL_HOST=db
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: nextcloud-redis
    ports:
      - 6379:6379 # You can specify your own port or configure a socket
    restart: unless-stopped

  imaginary:
    image: h2non/imaginary
    container_name: nextcloud-imaginary
    ports:
      - 9000:9000
    command: -enable-url-source -concurrency 20
    restart: unless-stopped

